#!/usr/bin/env ruby
require 'open3'

def self.copy_program
  %w[pbcopy xclip].find do |name|
    `which #{name}`
    $?.success?
  end
end

def self.copy_to_clipboard(str)
  Open3.popen3(copy_program) { |stdin, *| stdin.write str }
end

if ARGV.include?('-h') || ARGV.include?('--help')
  puts <<~HELP
  usage: fullpath *[relative-paths] [-c]

    Prints the fullpath of the paths
    If no paths are given as args, it will read them from stdin

    If there is only one path, the trailing newline is omitted

    The -c flag will copy the results into your pasteboard
  HELP
  exit true
end

# Process args
should_copy = ARGV.delete('-c') || ARGV.delete('--copy')

# Expand dirs
ARGV.replace $stdin.readlines.map &:chomp if ARGV.empty?
absolute_dirs = ARGV.reject(&:empty?).map { |path| File.expand_path path  }
absolute_dirs.each { |dir| dir << "\n" } unless absolute_dirs.one?
output = absolute_dirs.join("")

# Output
print output
copy_to_clipboard output if should_copy
