language: ruby
install:
  - gem install bundler && bundle install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start (from travis docs)
script: bundle exec rake ruby
rvm:
  - 2.3.1
addons:
  apt:
    packages:
    - xclip
