#!/usr/bin/env ruby
require 'bundler/setup'

root_path    = File.expand_path '.', __dir__
lang_pattern = File.join root_path, '*'
all_langs    = Dir.glob(lang_pattern)
                  .select { |dir| Dir.exist? dir }
                  .map    { |dir| File.basename dir }
                  .reject { |dir| 'features' == dir }

langs_to_test = ARGV.flat_map do |dir|
  if dir == 'all'
    all_langs
  elsif all_langs.include? dir
    [dir]
  else
    raise "Unknown language: #{dir.inspect}, choose \"all\", or any set of: #{all_langs.inspect}"
  end
end

langs_to_test = all_langs if langs_to_test.empty?

original_path = ENV['PATH']
langs_to_test.each do |lang|
  puts "\e[35m=====  #{lang}  =====\e[39m"
  ENV['FULLPATH_DIR'] = File.join(root_path, lang)
  pid                 = spawn 'cucumber'
  Process.wait pid
  exit $?.exitstatus unless $?.success?
end
