#!/usr/bin/env lua

local lfs = require("lfs")
local cwd = lfs.currentdir()
local sep = "/"

local function join(dir, entry)
  return dir .. sep .. entry
end

local function getEach(table)
  local element
  local getter, constant, state = ipairs(table)
  return function()
    state, element = getter(constant, state)
    return element
  end
end

function printEach(eachFilename)
  local i = 0
  for entry in eachFilename do
    if entry ~= "" then
      i = i + 1
      if i == 2 then io.write("\n") end
      io.write(join(cwd, entry))
      if i ~= 1 then io.write("\n") end
    end
  end
end

local showHelp = false
local filenames = {}
for i, arg in ipairs(arg) do
  if arg == "-h" or arg == "--help" then
    showHelp = true
  else
    table.insert(filenames, arg)
  end
end

if showHelp then
  print("usage: fullpath *[relative-paths] [-c]")
  print()
  print("  Prints the fullpath of the paths")
  print("  If no paths are given as args, it will read them from stdin")
  print()
  print("  If there is only one path, the trailing newline is omitted")
  print()
  print("  The -c flag will copy the results into your pasteboard")
elseif #filenames == 0 then
  printEach(io.lines())
else
  printEach(getEach(filenames))
end
