#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose
main(Args) ->
  {ok, Cwd} = file:get_cwd(),
  if
    Args == [] ->
      RawLine  = io:get_line(""),
      LineNoNl = re:replace(RawLine, "\n$", "", [global,{return,list}]),
      Paths    = [LineNoNl],
      print_path(Cwd, Paths, trailing_str(Paths));
    true ->
      print_paths(Cwd, Args, trailing_str(Args))
  end.

print_paths(_, [], _) ->
  init:stop();

print_paths(Cwd, [Path|Rest], Nl) ->
  print_path(Cwd, Path, Nl),
  print_paths(Cwd, Rest, Nl).

print_path(Cwd, Path, TrailingStr) ->
  io:format("~s/~s~s", [Cwd, Path, TrailingStr]).

trailing_str([]) -> "";
trailing_str([_|Rest]) ->
  if
    [] == Rest -> "";
    true       -> "\n"
  end.

% main(_) ->
%   usage().

% usage() ->
%   io:format("usage: factorial integer\n"),
%   halt(1).
