#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose
main(Args) ->
  {ok, Cwd} = file:get_cwd(),
  if
    Args == [] ->
      Line  = strip_newline(io:get_line("")),
      Paths = filter_blanks([Line]);
    true ->
      Paths = filter_blanks(Args)
  end,
  print_paths(Cwd, Paths, trailing_str(Paths)).

strip_newline(eof)  -> eof;
strip_newline(Line) -> re:replace(Line, "\n$", "", [global,{return,list}]).

filter_blanks([])          -> [];
filter_blanks([eof|Rest])  -> filter_blanks(Rest);
filter_blanks([""|Rest])   -> filter_blanks(Rest);
filter_blanks([Path|Rest]) -> [Path | filter_blanks(Rest)].

print_paths(_, [], _) ->
  init:stop();
print_paths(Cwd, [Path|Rest], Nl) ->
  print_path(Cwd, Path, Nl),
  print_paths(Cwd, Rest, Nl).

print_path(Cwd, Path, TrailingStr) ->
  io:format("~s/~s~s", [Cwd, Path, TrailingStr]).

trailing_str([])  -> "";
trailing_str([_]) -> "";
trailing_str(_)   -> "\n".
