#!/usr/bin/env bash

set -eu
set -o pipefail

sdk_path=`xcrun --show-sdk-path --sdk macosx`
swiftc -o fullpath -sdk "$sdk_path" Fullpath.swift &&
  echo &&
  ./fullpath a b '' c &&
  echo &&
  printf stdin1\\nstdin2 | ./fullpath &&
  echo &&
  printf stdin3\\nstdin4 | ./fullpath &&
  echo &&
  ./fullpath single
