#!/bin/sh

builddir="build"
metadata_dir="META-INF"
manifest="MANIFEST.MF"
mainclass="Fullpath"
executable="fullpath"

# Setup: delete old build, make new build dirs
cd "$(dirname "$0")"
rm -r $builddir
mkdir -p "$builddir/$metadata_dir"

# Make the manifest file
echo "Manifest-Version: 1.0"  >  "$builddir/$metadata_dir/$manifest"
echo "Created-By: Josh Cheek" >> "$builddir/$metadata_dir/$manifest"
echo "Main-Class: $mainclass" >> "$builddir/$metadata_dir/$manifest"
echo                          >> "$builddir/$metadata_dir/$manifest" # TODO: do I need this?

# Build it
javac -d "$builddir" -Xlint:unchecked "${mainclass}.java"      # Compile Java
pushd "$builddir"
jar cvmf "$metadata_dir/$manifest" "${mainclass}.jar" *.class  # Archive
popd

# Consolidate into an executable
echo "#!/usr/bin/env java -jar"   >  "$executable"
cat "$builddir/${mainclass}.jar"  >> "$executable"
chmod "+x" "$executable"

echo "========= TEST ============="
./"$executable" a b c '' d -x
