#!/usr/bin/env python
import sys
import os

# sys.stdin
# sys.stdout

def normalize(lines):
    lines = map(lambda x:x.strip(), lines)
    lines = filter(lambda x:x!="", lines)
    return lines

def printLines(lines):
    if len(lines) == 1:
        sys.stdout.write(os.path.abspath(lines[0]))
    else:
        for path in lines:
            print(os.path.abspath(path))

args = sys.argv[1:]
if '-h' in args or '--help' in args:
    print """usage: fullpath *[relative-paths] [-c]

  Prints the fullpath of the paths
  If no paths are given as args, it will read them from stdin

  If there is only one path, the trailing newline is omitted

  The -c flag will copy the results into your pasteboard"""
    exit(0)
if len(args) == 0:
    lines = normalize(sys.stdin.readlines())
    printLines(lines)
else:
    printLines(normalize(args))
