#!/usr/bin/env python
import sys
import os

# sys.stdin
# sys.stdout

args = sys.argv[1:]

if len(args) == 0:
    lines = sys.stdin.readlines()
    for path in lines:
        sys.stdout.write(os.path.abspath(path))
else:
    if len(args) == 1:
        sys.stdout.write(os.path.abspath(args[0]))
    else:
        for path in args:
            print(os.path.abspath(path))
