#!/usr/bin/env julia

help  = false
copy  = false
dir   = pwd()
paths = []

for arg = ARGS
  if arg == "-h" || arg == "--help"
    help = true
  elseif arg == "-c" || arg == "--copy"
    copy = true
  else
    push!(paths, arg)
  end
end

if length(paths) == 0
  paths = map(chomp, readlines())
end

if length(paths) == 1
  path = paths[1]
  print("$dir/$path")
else
  for path = paths
    println("$dir/$path")
  end
end
