file 'FullpathKt.class' => 'fullpath.kt' do
  sh 'kotlinc fullpath.kt'
end

task "run" => 'FullpathKt.class' do
  sh "./fullpath", "a\nb", "", "c"
  sh "ruby -e 'puts %(x\ny\n\nz)' | ./fullpath"
  sh "./fullpath", "no-newline"
end
