task default: 'run'

file 'fullpath.jar' => 'fullpath.kt' do
  sh 'kotlinc',
     '-include-runtime',
     '-d', 'fullpath.jar',
     'fullpath.kt'
end

file 'fullpath' => 'Rakefile'
file 'fullpath' => 'fullpath.jar' do
  sh 'echo "#!/usr/bin/env java -jar" >  fullpath'
  sh 'cat fullpath.jar                >> fullpath'
  chmod '+x', 'fullpath'
end

task 'run' => 'fullpath' do
  sh "./fullpath", "a\nb", "", "c"
  sh "ruby -e 'puts %(x\ny\n\nz)' | ./fullpath"
  sh "./fullpath", "no-newline"
end
