file 'FullpathKt.class' => 'fullpath.kt' do
  sh 'kotlinc fullpath.kt'
end

task "run" => 'FullpathKt.class' do
  sh "./fullpath", "a\nb", "", "c"
  sh "ruby -e 'puts %(a\nb\n\nc)' | ./fullpath"
  sh "./fullpath", "a"
end
