#!/usr/bin/env fish

# process args into these three vars
set paths
set printHelp false
set copyOutput true

for arg in $argv
  if test $arg = "-h"; or test $arg = "--help"
    set printHelp true
  else if test $arg = "-c"; or test $arg = "--copy"
    set copyOutput false
  else if test -n $arg
    set paths $paths $arg
  end
end

# read paths from stdin if none were provided
if test (count $paths) -eq 0
  while read -l line
    if test -n $line
      set paths $paths $line
    end
  end
end

if test (count $paths) -eq 1
  echo -n $PWD/$paths[1]
else
  for arg in $paths
    echo $PWD/$arg
  end
end
