#!/usr/bin/env php --no-php-ini
<?php

  function print_help() { ?>
usage: fullpath *[relative-paths] [-c]

  Prints the fullpath of the paths
  If no paths are given as args, it will read them from stdin

  If there is only one path, the trailing newline is omitted

  The -c flag will copy the results into your pasteboard
<?php }


  function paths_in($paths) {
    return(array_filter($paths, function($str) {
      return($str != "" && $str[0] != "-");
    }));
  }

  function absolute_paths($cwd, $relative_paths) {
    $make_absolute = function($path) use ($cwd) { return("$cwd/$path"); };
    return(array_map($make_absolute, $relative_paths));
  }

  function read_paths($stream) {
    $paths = array();
    while($f = fgets($stream)) array_push($paths, rtrim($f, "\n"));
    return($paths);
  }

  function print_paths($stream, $paths) {
    $delimiter = (count($paths) == 1 ? "" : "\n");
    foreach ($paths as $index => $path)
      fwrite($stream, "$path$delimiter");
  }

  $print_help = in_array("-h", $argv, true) || in_array("--help", $argv, true);

  if ($print_help) {
    print_help();
  } else {
    $paths = paths_in(array_slice($argv, 1));
    if(count($paths) == 0) $paths = read_paths(STDIN);
    $paths = absolute_paths(getcwd(), $paths);
    print_paths(STDOUT, $paths);
    /* if should copy */
    /*   copy paths */
  }
?>
