#!/usr/bin/env php --no-php-ini
<?php
  main(array_slice($argv, 1), STDIN, STDOUT, getcwd()); // $argv[0] is the filename

  function print_help() { ?>
usage: fullpath *[relative-paths] [-c]

  Prints the fullpath of the paths
  If no paths are given as args, it will read them from stdin

  If there is only one path, the trailing newline is omitted

  The -c flag will copy the results into your pasteboard
<?php }

  function main($args, $stdin, $stdout, $cwd) {
    if (has_flags($args, "-h", "--help")) {
      print_help();
      return;
    }
    $paths = select_paths($args);
    if(empty($paths)) {
      $paths = select_paths(read_lines($stdin));
    }
    $paths = absolute_paths($cwd, $paths);
    $print_paths = function($stream) use ($paths) {
      print_paths($stream, $paths);
    };
    $print_paths($stdout);
    has_flags($args, "-c", "--copy") && pbcopy($print_paths);
  }

  function select_paths($paths) {
    return array_filter($paths, function($str) {
      return $str != "" && $str[0] != "-";
    });
  }

  function absolute_paths($cwd, $relative_paths) {
    $make_absolute = function($path) use ($cwd) { return "$cwd/$path"; };
    return array_map($make_absolute, $relative_paths);
  }

  function read_lines($stream) {
    $paths = array();
    while($f = fgets($stream)) array_push($paths, rtrim($f, "\n"));
    return $paths;
  }

  function print_paths($stream, $paths) {
    $delimiter = (count($paths) == 1 ? "" : "\n");
    foreach ($paths as $index => $path)
      fwrite($stream, "$path$delimiter");
  }

  function pbcopy($callback) {
    $process = proc_open('pbcopy', array(0 => array("pipe", "r")), $pipes);
    $callback($pipes[0]);
    fclose($pipes[0]);
    proc_close($process);
  }

  function has_flags($args /*, ...$flags */) {
    $flags = array_slice(func_get_args(), 1); // first arg is `$args`
    $found = array_intersect($args, $flags);
    return !empty($found);
  }
?>
