#!/usr/bin/env php
<?php function print_help() { ?>
usage: fullpath *[relative-paths] [-c]

  Prints the fullpath of the paths
  If no paths are given as args, it will read them from stdin

  If there is only one path, the trailing newline is omitted

  The -c flag will copy the results into your pasteboard
<?php }

  $print_help = in_array("-h", $argv, true) || in_array("--help", $argv, true);

  if ($print_help) {
    print_help();
  }
  /* else */
  /*   paths = normalize argv */
  /*   if no paths */
  /*     paths = read stdin and normalize */
  /*   print paths */
  /*   if should copy */
  /*     copy paths */
?>
